// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFnf1g0_KSAM8yXqnoALmpfkdLxRp9ZgI',
    appId: '1:423289236248:web:25772425b81183897f8c6d',
    messagingSenderId: '423289236248',
    projectId: 'the-pegasus-school-map',
    authDomain: 'the-pegasus-school-map.firebaseapp.com',
    storageBucket: 'the-pegasus-school-map.firebasestorage.app',
    measurementId: 'G-G3QPH7BV43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3el6YDvEbdMpWwsY4HcJVfcsYaO2ayg0',
    appId: '1:423289236248:android:c8ddd5aec89bf1027f8c6d',
    messagingSenderId: '423289236248',
    projectId: 'the-pegasus-school-map',
    storageBucket: 'the-pegasus-school-map.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM4RrowAfAif7xhQmVgVnpAx960DTNCsA',
    appId: '1:423289236248:ios:94f03a7b9ac4d8cc7f8c6d',
    messagingSenderId: '423289236248',
    projectId: 'the-pegasus-school-map',
    storageBucket: 'the-pegasus-school-map.firebasestorage.app',
    iosBundleId: 'com.pegasusschool.findYourWayAround',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM4RrowAfAif7xhQmVgVnpAx960DTNCsA',
    appId: '1:423289236248:ios:94f03a7b9ac4d8cc7f8c6d',
    messagingSenderId: '423289236248',
    projectId: 'the-pegasus-school-map',
    storageBucket: 'the-pegasus-school-map.firebasestorage.app',
    iosBundleId: 'com.pegasusschool.findYourWayAround',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFnf1g0_KSAM8yXqnoALmpfkdLxRp9ZgI',
    appId: '1:423289236248:web:a10fb9b564c08f1a7f8c6d',
    messagingSenderId: '423289236248',
    projectId: 'the-pegasus-school-map',
    authDomain: 'the-pegasus-school-map.firebaseapp.com',
    storageBucket: 'the-pegasus-school-map.firebasestorage.app',
    measurementId: 'G-FNN9F49L61',
  );
}
